name: Build and Deploy DocFX Site

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  repository_dispatch:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  test:    
    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        configuration: [Release]

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore project
        run: dotnet restore src

      - name: Run tests
        run: |
          cd ${{ vars.PATH_TO_TESTS }}
          ls -a
          dotnet test -c ${{ matrix.configuration }} ${{ vars.PATH_TO_TESTS }}

  build_static_html:
    name: Build to static HTML  
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install DocFX
        run: dotnet tool install -g docfx

      - name: Build Documentation
        run: docfx docs/docfx.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./docs/_site

  deploy_pages:
    needs: build_static_html
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
