name: Run tests and publish to NuGet

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
  repository_dispatch:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        configuration: [Release]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore project
        run: dotnet restore src

      - name: Run tests
        run: |
          cd ${{ vars.SRC_FOLDER }}
          dotnet test -c ${{ matrix.configuration }} ${{ vars.TESTS_FOLDER }}

  tag-and-publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore project
        run: dotnet restore src

      - name: Configure Git
        run: |
          git config --global user.email "name@lcma.xyz"
          git config --global user.name "Name"

      - name: Determine if ResultSharp.Logging.Serilog has changes
        id: serilog_changes
        run: |
          if [ $(git rev-parse --is-shallow-repository) = true ]; then
            git fetch --unshallow
          fi
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            if git diff --name-only HEAD^ HEAD | grep -q '^src/ResultSharp.Logging.Serilog/'; then echo "serilog_changed=true" >> $GITHUB_ENV; else echo "serilog_changed=false" >> $GITHUB_ENV; fi
          else
            echo "serilog_changed=true" >> $GITHUB_ENV
          fi

      - name: Determine if ResultSharp.Logging.MicrosoftLogger has changes
        id: microsoftlogger_changes
        run: |
          if [ $(git rev-parse --is-shallow-repository) = true ]; then
            git fetch --unshallow
          fi
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            if git diff --name-only HEAD^ HEAD | grep -q '^src/ResultSharp.Logging.MicrosoftLogger/'; then echo "microsoft_logger_changed=true" >> $GITHUB_ENV; else echo "microsoft_logger_changed=false" >> $GITHUB_ENV; fi
          else
            echo "microsoft_logger_changed=true" >> $GITHUB_ENV
          fi

      - name: Determine if ResultSharp has changes
        id: resultsharp_changes
        run: |
          if [ $(git rev-parse --is-shallow-repository) = true ]; then
            git fetch --unshallow
          fi
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            if git diff --name-only HEAD^ HEAD | grep -q '^src/ResultSharp/'; then echo "resultsharp_changed=true" >> $GITHUB_ENV; else echo "resultsharp_changed=false" >> $GITHUB_ENV; fi
          else
            echo "resultsharp_changed=true" >> $GITHUB_ENV
          fi

      - name: Publish ResultSharp.Logging.Serilog if changed
        if: env.serilog_changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          echo "Getting version for ResultSharp.Logging.Serilog..."
          version=$(grep '<Version>' src/ResultSharp.Logging.Serilog/ResultSharp.Logging.Serilog.csproj | sed -E 's/.*<Version>([^<]+)<\/Version>.*/\1/') || { echo "Failed to get version"; exit 1; }
          version="v$version"
          echo "Version: $version"
          git tag -a "ResultSharp.Logging.Serilog.$version" -m "Release $version" || { echo "Failed to create tag"; exit 1; }
          git push origin "ResultSharp.Logging.Serilog.$version" || { echo "Failed to push tag"; exit 1; }
          dotnet pack src/ResultSharp.Logging.Serilog/ResultSharp.Logging.Serilog.csproj -c Release -o out || { echo "Failed to pack"; exit 1; }
          dotnet nuget push "out/*.nupkg" -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate -s https://api.nuget.org/v3/index.json || { echo "Failed to push NuGet package"; exit 1; }

      - name: Publish ResultSharp.Logging.MicrosoftLogger if changed
        if: env.microsoft_logger_changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          echo "Getting version for ResultSharp.Logging.MicrosoftLogger..."
          version=$(grep '<Version>' src/ResultSharp.Logging.MicrosoftLogger/ResultSharp.Logging.MicrosoftLogger.csproj | sed -E 's/.*<Version>([^<]+)<\/Version>.*/\1/') || { echo "Failed to get version"; exit 1; }
          version="v$version"
          echo "Version: $version"
          git tag -a "ResultSharp.Logging.MicrosoftLogger.$version" -m "Release $version" || { echo "Failed to create tag"; exit 1; }
          git push origin "ResultSharp.Logging.MicrosoftLogger.$version" || { echo "Failed to push tag"; exit 1; }
          dotnet pack src/ResultSharp.Logging.MicrosoftLogger/ResultSharp.Logging.MicrosoftLogger.csproj -c Release -o out || { echo "Failed to pack"; exit 1; }
          dotnet nuget push "out/*.nupkg" -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate -s https://api.nuget.org/v3/index.json || { echo "Failed to push NuGet package"; exit 1; }

      - name: Publish ResultSharp if changed
        if: env.resultsharp_changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          echo "Getting version for ResultSharp..."
          version=$(grep '<Version>' src/ResultSharp/ResultSharp.csproj | sed -E 's/.*<Version>([^<]+)<\/Version>.*/\1/') || { echo "Failed to get version"; exit 1; }
          version="v$version"
          echo "Version: $version"
          git tag -a "ResultSharp.$version" -m "Release $version" || { echo "Failed to create tag"; exit 1; }
          git push origin "ResultSharp.$version" || { echo "Failed to push tag"; exit 1; }
          dotnet pack src/ResultSharp/ResultSharp.csproj -c Release -o out || { echo "Failed to pack"; exit 1; }
          dotnet nuget push "out/*.nupkg" -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate -s https://api.nuget.org/v3/index.json || { echo "Failed to push NuGet package"; exit 1; }
